In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, StratifiedShuffleSplit, RepeatedKFold, train_test_split
import math
import statistics

# DATASET 1
## Breast Cancer Dataset

In [5]:
dataset = pd.read_csv(r"D:\FastSemesters\semester5\ML\lab\breastCancer.csv")
dataset.drop('id',axis=1,inplace=True)
dataset.drop('Unnamed: 32',axis=1,inplace=True)
dataset['diagnosis'] = dataset['diagnosis'].map({'M':1,'B':0})
dataset

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [6]:
# 10X10 FOLD CV
array = dataset.values
X = array[:,1:30]
Y = array[:,0]

CV = RepeatedKFold(n_splits = 10, n_repeats = 10, random_state = 1)

In [7]:
# Decision Tree using gini (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='gini')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.93
Standard Deviation:  0.03

In [8]:
# Decision Tree using gini (pruning parameter)
dt = DecisionTreeClassifier( criterion='gini', ccp_alpha = 0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.92
Standard Deviation:  0.03

In [9]:
# Decision Tree using Entropy (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='entropy')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.93
Standard Deviation:  0.03

In [10]:
# Decision Tree using Entropy (pruning parameter)
dt= DecisionTreeClassifier( criterion='entropy', ccp_alpha= 0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.93
Standard Deviation:  0.03

In [11]:
# hold out 100 times
array = dataset.values
X = array[:,1:30]
Y = array[:,0]
CV2 = StratifiedShuffleSplit(n_splits=100, test_size=0.3, random_state=0)

In [12]:
# Decision Tree using gini (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='gini')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.92
Standard Deviation:  0.03

In [13]:
# Decision Tree using gini (with pruning parameter)
dt = DecisionTreeClassifier( criterion='gini', ccp_alpha=0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.92
Standard Deviation:  0.03

In [14]:
# Decision Tree using Entropy (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='entropy')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.93
Standard Deviation:  0.03

In [15]:
# Decision Tree using Entropy (pruning parameter)
dt= DecisionTreeClassifier( criterion='entropy', ccp_alpha= 0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.93
Standard Deviation:  0.03

# DATASET 2
## DEATH DUE TO HEART FAILURE

In [16]:
data = pd.read_csv(r"D:\FastSemesters\semester5\ML\lab\heartfailure\heart_failure_clinical_records_dataset.csv")
data.replace(['?', 'NULL'], 0)
data

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [17]:
# 10X10 FOLD CV
array = data.values
X = array[:,0:12]
Y = array[:,12]

CV = RepeatedKFold(n_splits = 10, n_repeats = 10, random_state = 1)

In [18]:
# Decision Tree using gini (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='gini')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.77
Standard Deviation:  0.07

In [19]:
# Decision Tree using gini (pruning parameter)
dt = DecisionTreeClassifier( criterion='gini', ccp_alpha = 0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.82
Standard Deviation:  0.07

In [20]:
# Decision Tree using Entropy (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='entropy')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.78
Standard Deviation:  0.08

In [21]:
# Decision Tree using Entropy (pruning parameter)
dt= DecisionTreeClassifier( criterion='entropy', ccp_alpha= 0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.79
Standard Deviation:  0.07

In [22]:
# hold out 100 times
array = data.values
X = array[:,0:12]
Y = array[:,12]
CV2 = StratifiedShuffleSplit(n_splits=100, test_size=0.3, random_state=0)

In [23]:
# Decision Tree using gini (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='gini')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.78
Standard Deviation:  0.07

In [24]:
# Decision Tree using gini (with pruning parameter)
dt = DecisionTreeClassifier( criterion='gini', ccp_alpha=0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.82
Standard Deviation:  0.07

In [25]:
# Decision Tree using Entropy (with out pruning parameter)
dt = DecisionTreeClassifier( criterion='entropy')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.79
Standard Deviation:  0.08

In [26]:
# Decision Tree using Entropy (pruning parameter)
dt= DecisionTreeClassifier( criterion='entropy', ccp_alpha= 0.015)
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.79
Standard Deviation:  0.08

In [27]:
# Decision Roots using Enthalpy (with out pruning parameter)
dt = DecisionTreeClassifier( criterion= 'entropy')
Acc_n_Std = cross_val_score(dt, X, Y, scoring='accuracy', cv=CV, n_jobs = -1)
print('Accuracy: ', round(np.mean(Acc_n_Std),2))
print('Standard Deviation: ',round(np.std(Acc_n_Std),2))

Accuracy:  0.78
Standard Deviation:  0.08

# QUESTION #02

In [28]:
#Second task is to find out root node of decision tree from scratch on above dataset of
#(outlook, temperature, humidity, windy) using ID3 algorithm. You can create this dataset in excel
#file.

In [3]:
d = pd.read_excel(r"D:\FastSemesters\semester5\ML\lab\outlook.xlsx")
d

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [39]:
entropy = -(9/14)*np.log(9/14) - (5/14)*np.log(5/14)
entropySunny = -(2/5)*np.log(2/5) - (3/5)*np.log(3/5) 
entropyOvercast = -(4/4)*np.log2(4/4) - 0
entropyRainy = -(3/5)*np.log(3/5) - (2/5)*np.log(2/5) 
entropyOutcast = (5/14)*(entropySunny)+(5/14)*(entropyRainy)+(4/14)*(entropyOvercast)
print(entropyOutcast)

0.48072261929232607

In [40]:
print(entropy)

0.6517565611726531

In [9]:
def rootNode(Dataset):
  infogains = []
  for columns in d.columns:
    if columns != 'PlayTennis':
      infogains.append([columns,Informationgain(columns,Dataset)])
  infogains = sorted(infogains,key = lambda x:x[1],reverse = True)
  print("Root Node:",infogains[0][0])

def Informationgain(column,DataSet):
  values = DataSet[column]
  totalvalues = values.unique()
  values = list(DataSet[column])
  entropy = 0
  for a in totalvalues:
    entropy -= (values.count(a)/len(values)) * math.log2((values.count(a)/len(values)))
  return entropy

rootNode(d)

Root Node: outlook